-- Для @GeneratedValue(strategy = GenerationType.IDENTITY)
/*
create table client
(
    id   bigserial not null primary key,
    name varchar(50)
);

 */

-- Для @GeneratedValue(strategy = GenerationType.SEQUENCE)
create sequence client_SEQ start with 1 increment by 1;

create table client
(
    address_id bigint unique,
    id bigint not null,
    name varchar(255), primary key (id)
);

create table address
(
   id bigint generated by default as identity,
   street varchar(255),
   primary key (id)
);

create table phone
(
    client_id bigint,
    id bigint generated by default as identity,
    phonenumber varchar(255),
    primary key (id)
);

alter table if exists client add constraint FKb137u2cl2ec0otae32lk5pcl2 foreign key (address_id) references address;

alter table if exists phone add constraint FK3o48ec26lujl3kf01hwqplhn2 foreign key (client_id) references client;

